INSERT INTO CLIENT(NAME,LAST_NAME,ADDRESS) VALUES ('PATRYK','KANIA','MALINOWA 12, 110-12 KATOWICE')
INSERT INTO CLIENT(NAME,LAST_NAME,ADDRESS) VALUES ('TOMASZ','NOWAK','BAZIOWA 22, 110-12 KATOWICE')

INSERT INTO PRODUCT(NAME,PRICE) VALUES ('T-SHIRT', 22.00)
INSERT INTO PRODUCT(NAME,PRICE) VALUES ('SPODNIE', 122.00)
INSERT INTO PRODUCT(NAME,PRICE) VALUES ('BLUZA', 99.00)
INSERT INTO PRODUCT(NAME,PRICE) VALUES ('SUKIENKA', 250.99)

INSERT INTO ORDERS(ADDITIONAL_MSG,CLIENT_ID) VALUES ('PROSZE O SZYBKA WYSYLKE', 1)
INSERT INTO ORDERS(ADDITIONAL_MSG,CLIENT_ID) VALUES ('', 1)
INSERT INTO ORDERS(ADDITIONAL_MSG,CLIENT_ID) VALUES ('', 2)

INSERT INTO ORDERS_PRODUCTS(ORDERS_ID, PRODUCTS_ID) VALUES (1,1)
INSERT INTO ORDERS_PRODUCTS(ORDERS_ID, PRODUCTS_ID) VALUES (1,2)
INSERT INTO ORDERS_PRODUCTS(ORDERS_ID, PRODUCTS_ID) VALUES (2,2)
INSERT INTO ORDERS_PRODUCTS(ORDERS_ID, PRODUCTS_ID) VALUES (3,2)
INSERT INTO ORDERS_PRODUCTS(ORDERS_ID, PRODUCTS_ID) VALUES (3,3)
INSERT INTO ORDERS_PRODUCTS(ORDERS_ID, PRODUCTS_ID) VALUES (3,4)






